const Products = [
    {
        id: 1,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782334763/1_1_lujzyr.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782334763/1_2_nympsg.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782334783/1_3_yluqh1.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782334875/1_4_nbqccl.webp'],
        size : 'sm',
        rating : '3'
    },
    {
        id: 2,
        title: "m-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 50,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782334967/2_1_vdlikt.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335217/2_2_lg8or2.webp'],
        size : 'md',
        rating : '4'
    },
    {
        id: 3,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 120,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335074/3_1_oxcggn.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335074/3_2_v5qyxa.webp', 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335097/3_3_yqh5dg.webp'],
        size : 'sm',
        rating : '5'
    },
    {
        id: 4,
        title: "z-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 200,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335236/4_1_hwlsul.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335236/4_2_yiq33n.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335236/4_3_r9cv9r.jpg'],
        size : 'lg',
        rating : '3'
    },
    {
        id: 5,
        title: "e-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 45,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335306/5_1_dxsefb.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335306/5_2_wxas7k.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335331/5_3_evn6tr.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335307/5_4_dcrggf.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 6,
        title: "k-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 166,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335385/6_1_va4qsd.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335385/6_1_va4qsd.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335361/6_2_v8r1zl.jpg'],
        size : 'xxl',
        rating : '2'
    },
    {
        id: 7,
        title: "a-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 80,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335443/7_1_kdfoet.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335434/7_2_i1zdr7.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335434/7_3_xlw2se.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335435/7_4_l95amh.webp'],
        size : 'md',
        rating : '5'
    },
    {
        id: 8,
        title: "w-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 61,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335509/8_1_u28psb.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335509/8_2_etn84y.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335509/8_3_gju6zs.webp'],
        size : 'lg',
        rating : '4'
    },
    {
        id: 9,
        title: "o-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 200,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335510/9_1_rxcmqx.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335511/9_2_wfkwlr.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335512/9_3_ycv9eg.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335513/9_4_zqx3vc.jpg'],
        size : 'xxl',
        rating : '3'
    },
    {
        id: 10,
        title: "p-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 270,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335583/10_1_n9h6dj.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335633/10_2_qupiac.jpg'],
        size : 'md',
        rating : '1'
    },
    {
        id: 11,
        title: "r-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 20,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335584/11_1_wggoy8.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335585/11_2_wmiht8.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335586/11_3_moa4rh.jpg'],
        size : 'sm',
        rating : '5'
    },
    {
        id: 12,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 366,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335691/12_1_vanpem.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335662/12_2_itiiaz.jpg'],
        size : 'sm',
        rating : 2
    },
    {
        id: 13,
        title: "x-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 99,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335665/13_1_tuhwpg.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335666/13_2_hthzmg.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335693/13_3_sj50ow.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335666/13_4_nkiqvd.webp'],
        size : 'lg',
        rating : '5'
    },
    {
        id: 14,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 55,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335756/14_1_anvwo9.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335751/14_2_vdzvht.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335752/14_3_mecjyp.webp'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 15,
        title: "g-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 77,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335766/15_1_q7wwwp.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335754/15_2_jmnewy.webp'],
        size : 'xxl',
        rating : '3'
    },
    {
        id: 16,
        title: "k-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 33,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335754/16_1_dzkiyx.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335755/16_2_sttdxp.jpg'],
        size : 'xxl',
        rating : '4'
    },
    {
        id: 17,
        title: "l-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 84,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335964/17_1_aitfkd.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335956/17_2_rawtut.webp'],
        size : 'md',
        rating : '1'
    },
    {
        id: 18,
        title: "m-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 268,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335836/18_1_mkbeqw.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335837/18_2_jv2t6l.webp'],
        size : 'lg',
        rating : '2'
    },
    {
        id: 19,
        title: "b-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 154,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782335839/19_1_g0wkxj.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782335959/19_2_eib3tg.jpg','https://res.cloudinary.com/dbggryeo1/image/upload/v1782335841/19_3_tteatk.jpg'],
        size : 'lg',
        rating : '5'
    },
    {
        id: 20,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 122,
        category: "fashion",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336024/20_1_qjwcmh.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336019/20_2_kvg1xl.webp'],
        size : 'sm',
        rating : '4'
    },
    {
        id: 21,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 370,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336020/21_1_grlypi.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336021/21_2_efwugv.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336022/21_3_d5896r.jpg  '],
        size : 'md',
        rating : '1'
    },
    {
        id: 22,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "bags",
        sub_category : 'women',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336131/22_1_chnejp.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336093/22_2_y5pzqx.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336095/22_3_xyel3g.jpg'],
        rating : '3'
    },
    {
        id: 23,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336120/23_1_r9higv.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336098/23_2_hut8oe.jpg'],
        rating : '1'
    },
    {
        id: 24,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336180/24_1_pfchvp.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336182/24_2_pc2ujr.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336183/24_3_lyqa7n.webp'],
        rating : '4'
    },
    {
        id: 25,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336184/25_1_oihmkt.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336186/25_2_e2uwqg.jpg']
    },
    {
        id: 26,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336188/26_1_ce0fja.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336189/26_2_iadl46.jpg']
    },
    {
        id: 27,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336277/27_1_iwj1qk.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336278/27_2_b5xm3c.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336279/27_3_ih2ify.jpg']
    },
    {
        id: 28,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '1',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336281/28_1_rwxlkg.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336374/28_2_q7vfob.jpg']
    },
    {
        id: 29,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '3',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336296/29_1_wz8vwa.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336397/29_2_lsqgqs.jpg']
    },
    {
        id: 30,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336448/30_1_ya6ni9.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336449/30_2_w9nti3.jpg']
    },
    {
        id: 31,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336451/31_1_ixwwsp.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336452/31_2_wygp7v.webp']
    },
    {
        id: 32,
        title: "n-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336453/32_1_wqt9qv.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336454/32_2_hbradc.jpg']
    },
    {
        id: 33,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "footwear",
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336456/33_1_ihmbbg.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336457/33_2_skn1vs.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336459/33_3_fvsfwn.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336460/33_4_syoyr2.jpg']
    },
    {
        id: 34,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "bags",
        sub_category : 'men',
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336552/34_1_nqtjgg.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336553/34_2_evdnb0.jpg']
    },
    {
        id: 35,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "bags",
        sub_category : 'men',
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336555/35_1_h4vf4j.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336575/35_2_xivm5a.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336717/35_3_d5o3in.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336652/35_4_yvuyl8.jpg']
    },
    {
        id: 36,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "bags",
        sub_category : 'men',
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336560/36_2_ldgrtw.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336560/36_2_ldgrtw.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336563/36_4_xya1c0.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336563/36_4_xya1c0.webp'  , 'img_36_6']
    },
    {
        id: 37,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'labtop',
        brand : 'nike',
        rating : '1',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336767/37_1_xqse0u.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336754/37_2_vgoftl.webp']
    },
    {
        id: 38,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336755/38_1_fzrphq.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336756/38_2_paqwhe.jpg']
    },
    {
        id: 39,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336758/39_1_yijeax.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336759/39_2_xrtizz.webp']
    },
    {
        id: 40,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'watch',
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336761/40_1_xkfxmc.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336762/40_2_e1ufoe.webp']
    },
    {
        id: 41,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'watch',
        brand : 'nike',
        rating : '1',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336870/41_1_kmgglv.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336870/41_2_lt1ipv.webp']
    },
    {
        id: 42,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'watch',
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336889/42_1_mi3bbn.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336877/42_2_wxqhoh.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336877/42_3_shnu2w.jpg']
    },
    {
        id: 43,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'labtop',
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336883/43_1_xoolss.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336884/43_2_ddj8jj.jpg']
    },
    {
        id: 44,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'labtop',
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782336886/44_1_gacaiz.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336888/44_2_qimndi.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782336889/44_3_eanxzn.webp']
    },
    {
        id: 45,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'labtop',
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337031/45_1_iskovk.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337034/45_2_pgawcm.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337034/45_3_c1fblm.webp']
    },
    {
        id: 46,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'labtop',
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337035/46_1_cychzc.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337137/46_2_u4jcxj.webp' ]
    },
    {
        id: 47,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'labtop',
        brand : 'nike',
        rating : '1',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337039/47_1_alwm36.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337135/47_2_ux9xym.webp']
    },
    {
        id: 48,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337042/48_1_yyqixp.webp']
    },
    {
        id: 49,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'watch',
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337141/49_1_tljtvc.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337047/49_2_tajnzo.webp']
    },
    {
        id: 50,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'labtop',
        brand : 'nike',
        rating : '1',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782402301/50_1_jdlr8h.webp']
    },
    {
        id: 51,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'phone',
        brand : 'nike',
        rating : '3',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782402302/51_1_wo3ptf.webp']
    },
    {
        id: 52,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'phone',
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782402303/52_1_uqxh81.webp']
    },
    {
        id: 53,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "elec",
        sub_category : 'phone',
        brand : 'nike',
        rating : '3',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337313/53_1_xqrdu3.jpg']
    },
    {
        id: 54,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "jew",
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337294/54_1_fo2ter.webp']
    },
    {
        id: 55,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "jew",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337295/55_1_waamlf.webp']
    },
    {
        id: 56,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "jew",
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337297/56_1_krdwsc.jpg']
    },
    {
        id: 57,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "bags",
        sub_category : 'women',
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337329/57_1_z6yowz.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337590/57_2_gvr00q.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337301/57_3_j6gjny.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337302/57_4_lxrj0g.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337315/57_5_anfkp9.webp']
    },
    {
        id: 58,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "bags",
        sub_category : 'women',
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337306/58_1_cszqkc.jpg']
    },
    {
        id: 59,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "jew",
        brand : 'nike',
        rating : '3',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782402695/59_1_srr9im.jpg']
    },
    {
        id: 60,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "jew",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337310/60_1_lv75nn.jpg']
    },
    {
        id: 61,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337708/61_1_cexfcd.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337701/61_2_dgdu4p.jpg']
    },
    {
        id: 62,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '3',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337703/62_1_vuroif.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337710/62_2_tkjzyl.jpg']
    },
    {
        id: 63,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337706/63_1_xzwbab.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337708/63_2_v7y2n6.webp']
    },
    {
        id: 64,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337590/57_2_gvr00q.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337719/64_2_fdrwtu.jpg']
    },
    {
        id: 65,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '2',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782338078/65_1_od2ivk.webp']
    },
    {
        id: 66,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '1',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782337714/66_1_caiv6b.webp' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782337710/62_2_tkjzyl.jpg']
    },
    {
        id: 67,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '4',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782338099/67_1_gf958y.webp']
    },
    {
        id: 68,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782338091/68_1_kdquoa.jpg']
    },
    {
        id: 69,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '3',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782338092/69_1_dwnoip.jpg']
    },
    {
        id: 70,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "beauty",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782338094/70_1_vqn3kv.jpg']
    },
    {
        id: 71,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782462862/71_1_isr9dc.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782462865/71_2_vxvgom.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782462866/71_3_vrxlfe.jpg' ]
    },
    {
        id: 72,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782338230/72_1_fu5fyf.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782338347/72_3_hkkjkp.jpg']
    },
    {
        id: 73,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782384400/73_1_fpv0ak.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782384416/73_2_g1g7rm.jpg']
    },
    {
        id: 74,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782384736/74_1_u41w7s.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782385071/74_2_xqa46q.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782385434/74_3_ek7ge4.jpg']
    },
    {
        id: 75,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782387124/75_1_qwilie.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782387263/75_2_vjvyut.jpg']
    },
    {
        id: 76,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782397034/76_1_arufkx.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782397094/76_3_clfzaw.jpg']
    },
    {
        id: 77,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782404098/tomatoes_hq8w5i.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782402404/77_2_xv7n9a.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782403678/77_3_p8g8by.jpg']
    },
    {
        id: 78,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782460977/78_1_mbf7iv.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782460834/78_2_uxrbvz.jpg']
    },
    {
        id: 79,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782461370/79_1_pelnw7.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782461235/79_4_y0vlyl.jpg' ]
    },
    {
        id: 80,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782404587/80_1_ccgcv8.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782404151/product-img-2_nl5cne.jpg']
    },
    {
        id: 81,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782404776/81_1_l0twx2.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782404168/red_pepper_l4mfm6.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782404816/81_3_yymxom.jpg']
    },
    {
        id: 82,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782406446/82_1_hooc7j.jpg']
    },
    {
        id: 83,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782406728/83_1_kbihu5.jpg']
    },
    {
        id: 84,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782404979/84_1_djbbpl.jpg']
    },
    {
        id: 85,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782461525/85_2_jork31.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782461678/85_1_b5ovco.jpg']
    },
    {
        id: 86,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782461927/86_1_gkdv0c.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782461929/86_2_kcgkvs.jpg']
    },
    {
        id: 87,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782406628/87_1_rckfca.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782406071/87_2_gb5lgi.jpg']
    },
    {
        id: 88,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782405271/88_1_awpp3f.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782404201/product-img-3_ewecni.jpg']
    },
    {
        id: 89,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782462143/89_1_sgknwk.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782462144/89_2_slf0gu.jpg']
    },
    {
        id: 90,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782462287/90_1_uqp8ai.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782462288/90_2_ozqd0s.jpg']
    },
    {
        id: 91,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782405271/88_1_awpp3f.jpg']
    },
    {
        id: 92,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782462478/92_1_dzhlx4.jpg' , 'https://res.cloudinary.com/dbggryeo1/image/upload/v1782462480/92_2_wribpu.jpg']
    },
    {
        id: 93,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782462636/93_1_mbikcv.jpg' ,'https://res.cloudinary.com/dbggryeo1/image/upload/v1782462638/93_2_z4rkcy.jpg']
    },
    {
        id: 95,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782410301/95_1_rjh0ke.jpg']
    },
    {
        id: 96,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782405651/dill_i8iy5p.jpg']
    },
    {
        id: 97,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782407091/97_2_gcchfv.jpg' ]
    },
    {
        id: 98,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782406834/98_1_tgncr9.jpg']
    },
    {
        id: 99,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782399360/f5_jr0trm.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 100,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782399359/f4_akm23z.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 101,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782399200/f3_tmwb4v.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 102,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782398543/f1_tzgjkx.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 103,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782399360/f5_jr0trm.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 104,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782399896/f6_orjnbp.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 105,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782399896/f7_janklr.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 106,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400028/n4_ovzkst.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 106,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400026/n3_jhaj2q.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 107,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400025/n1_tefpa2.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 108,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782399998/f8_ctcltx.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 109,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400172/n8_rktjrc.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 110,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400165/n5_j4ilq7.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 111,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400167/n7_oy2hpo.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 112,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400166/n6_kbye1d.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 113,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400340/product-4_wwp0ub.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 114,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400337/n8_jmcnyr.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 115,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400336/n7_gu1da1.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 116,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400341/product-5_wldkjv.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 117,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400341/product-6_xrpgcz.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 118,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400349/product-1_xl3ps5.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 119,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400344/product-3_nxo2i5.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 120,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "fashion",
        sub_category : 'men',
        brand : 'nike',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782400342/product-7_exjxku.jpg'],
        size : 'xl',
        rating : '4'
    },
    {
        id: 121,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782404154/product-img-5_tyysfd.jpg']
    },
    {
        id: 122,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782404153/product-img-4_act8jb.jpg']
    },
    {
        id: 123,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782404159/spinach_dmxxuv.jpg']
    },
    {
        id: 124,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782470780/peas_rmspq5.jpg']
    },
    {
        id: 125,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782470693/artichoke_roj2vl.jpg']
    },
    {
        id: 126,
        title: "T-Shirt",
        desc : 'Embroidered Satin Saree...',
        regular_price : 120,
        sale_price : 100,
        category: "groc",
        brand : 'nike',
        rating : '5',
        imgs : ['https://res.cloudinary.com/dbggryeo1/image/upload/v1782470871/olive_thbzwz.jpg']
    },
]

export default Products;